/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HyButton: typeof import('hy-app')['HyButton']
    HyCell: typeof import('hy-app')['HyCell']
    HyGrid: typeof import('hy-app')['HyGrid']
    HyIcon: typeof import('hy-app')['HyIcon']
    HyInput: typeof import('hy-app')['HyInput']
    HyOverlay: typeof import('hy-app')['HyOverlay']
    HySlider: typeof import('hy-app')['HySlider']
    HySwitch: typeof import('hy-app')['HySwitch']
    HyText: typeof import('hy-app')['HyText']
    HyTransition: typeof import('hy-app')['HyTransition']
  }
}
