/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HyButton: typeof import('hfyk-app')['HyButton']
    HyCheckbox: typeof import('hfyk-app')['HyCheckbox']
    HyGrid: typeof import('hfyk-app')['HyGrid']
    HyIcon: typeof import('hfyk-app')['HyIcon']
    HyInput: typeof import('hfyk-app')['HyInput']
    HyOverlay: typeof import('hfyk-app')['HyOverlay']
    HyRadio: typeof import('hfyk-app')['HyRadio']
    HySlider: typeof import('hfyk-app')['HySlider']
    HySwitch: typeof import('hfyk-app')['HySwitch']
  }
}
