/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HySlider: typeof import('hfyk-app')['HySlider']
    HySubsection: typeof import('hfyk-app')['HySubsection']
    HySwiper: typeof import('hfyk-app')['HySwiper']
  }
}
